### ISSUE TITLE
Tela de início

### ISSUE THREAD

**Issue by Laysanha** [Laysanha/MyFirstProjectAndroid#1]
### To-do list
_Data de criação: 01/02/2024_

---
- [ ] Mostrar os cards criados:
  - [ ] Nome do card;
  - [ ] Data de criação;
  - [ ] Data de ultima atualização;
  - [ ] Conteúdo descritivo;
- [ ] Botão de criação de card
  - [ ] Floating action button
